Repository tenstorrent/tt-inference-server, pull requests merged in 2025-08, with the labels that each got.

#425 Add limit_samples parameter to EvalTask for faster development cycles
  evals/eval_config.py
  evals/run_evals.py
Labels: enhancement

#439 Fix: Environment variables not passed from ModelSpecTemplate to ModelSpec
  workflows/model_spec.py
Labels: bug

#449 Fix: Add MAX_PREFILL_CHUNK_SIZE env var to Qwen2.5 72B
  workflows/model_spec.py
Labels: bug, enhancement
